//List of countries
export const countriesAndCapitals = {
  Germany: 'Berlin',
  Azerbaijan: 'Baku',
  France: 'Paris',
  Spain: 'Madrid',
  Italy: 'Rome',
  'United Kingdom': 'London',
  Ukraine: 'Kyiv',
  Japan: 'Tokyo',
  Brazil: 'Brasília',
  Canada: 'Ottawa',
  Australia: 'Canberra',
  India: 'New Delhi',
  China: 'Beijing',
  'South Korea': 'Seoul',
  Mexico: 'Mexico City',
  Argentina: 'Buenos Aires',
  Turkey: 'Ankara',
  Egypt: 'Cairo',
  'South Africa': 'Pretoria',
  Nigeria: 'Abuja',
  Kenya: 'Nairobi',
  'Saudi Arabia': 'Riyadh',
  'United Arab Emirates': 'Abu Dhabi',
  Thailand: 'Bangkok',
  Vietnam: 'Hanoi',
  Greece: 'Athens',
  Sweden: 'Stockholm',
  Norway: 'Oslo',
  Denmark: 'Copenhagen',
  Finland: 'Helsinki',
};
