export const GAME_DATA = {
  Germany: 'Berlin',
  Azerbaijan: 'Baku',
  France: 'Paris',
  Spain: 'Madrid',
  Italy: 'Rome',
  'United Kingdom': 'London',
  Ukraine: 'Kyiv',
  Japan: 'Tokyo',
  Brazil: 'Brasília',
  Canada: 'Ottawa',
  Australia: 'Canberra',
  India: 'New Delhi',
  China: 'Beijing',
  'South Korea': 'Seoul',
  Mexico: 'Mexico City',
  Argentina: 'Buenos Aires',
  Turkey: 'Ankara',
  Egypt: 'Cairo',
  'South Africa': 'Pretoria',
  Nigeria: 'Abuja',
  Kenya: 'Nairobi',
  'Saudi Arabia': 'Riyadh',
  'United Arab Emirates': 'Abu Dhabi',
  Thailand: 'Bangkok',
  Vietnam: 'Hanoi',
  Greece: 'Athens',
  Sweden: 'Stockholm',
  Norway: 'Oslo',
  Denmark: 'Copenhagen',
  Finland: 'Helsinki',
  Portugal: 'Lisbon',
  Ireland: 'Dublin',
  Switzerland: 'Bern',
  Belgium: 'Brussels',
  Netherlands: 'Amsterdam',
  Luxembourg: 'Luxembourg City',
  Austria: 'Vienna',
  Czechia: 'Prague',
  Slovakia: 'Bratislava',
  Slovenia: 'Ljubljana',
  Croatia: 'Zagreb',
  Bosnia: 'Sarajevo',
  Serbia: 'Belgrade',
  Montenegro: 'Podgorica',
  Albania: 'Tirana',
  Macedonia: 'Skopje',
  Kosovo: 'Pristina',
  Romania: 'Bucharest',
  Bulgaria: 'Sofia',
};
